version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "18"

  jobs:
    pre_build:
      - jupyter-book build docs/

# No Sphinx
sphinx:
  builder: "none"

# Tell RTD where your generated HTML is
publish:
  html: docs/_build/html/

python:
  install:
    - requirements: docs/requirements.txt
