version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs/requirements.txt

# Tell RTD we're NOT using the Sphinx builder directly
# (Sphinx will still be used internally by Jupyter Book)
sphinx:
  configuration: false

# Use the Python Jupyter Book CLI explicitly
build:
  commands:
    - python -m jupyter_book build docs
