version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  jobs:
    build:
      steps:
        - name: Build docs with mystmd
          run: myst build docs --html --output-dir $READTHEDOCS_OUTPUT/html

python:
  install:
    - method: pip
      packages:
        - mystmd
