version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
<<<<<<< HEAD
    - requirements: docs/requirements.txt    # <--- THIS LINE IS MISSING!
=======
    - requirements: docs/requirements.txt # <--- THIS LINE IS MISSING!
>>>>>>> 5f3868bb38d397479eb0640929883b7e83d9e236
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
