version: 2

build:
  tools:
    python: "3.11"
  commands:
    - python -m pip install -r docs/requirements.txt
    - python -m jupyter_book build docs

# Disable Sphinx’s own builder (Jupyter Book handles it)
sphinx:
  configuration: false
