version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  commands:
    - python -m mystmd build docs --html --output-dir $READTHEDOCS_OUTPUT/html

python:
  install:
    - requirements: docs/requirements.txt
