version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt    # <--- THIS LINE IS MISSING!
    - method: pip
      path: .                           

sphinx:
  configuration: docs/conf.py
  